/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 44
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 73
#define ALIAS_COUNT 0
#define TOKEN_COUNT 55
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym__text_token1 = 2,
  aux_sym__not_token1 = 3,
  aux_sym__not_token2 = 4,
  aux_sym__not_token3 = 5,
  aux_sym__not_token4 = 6,
  anon_sym_LBRACE_PERCENT = 7,
  anon_sym_PERCENT_RBRACE = 8,
  sym_expression_begin = 9,
  sym_expression_end = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_LBRACE_POUND = 13,
  aux_sym_comment_token1 = 14,
  anon_sym_POUND_RBRACE = 15,
  anon_sym_if = 16,
  anon_sym_else = 17,
  anon_sym_elif = 18,
  anon_sym_endif = 19,
  anon_sym_for = 20,
  anon_sym_endfor = 21,
  anon_sym_in = 22,
  anon_sym_while = 23,
  anon_sym_endwhile = 24,
  anon_sym_block = 25,
  anon_sym_endblock = 26,
  anon_sym_extends = 27,
  anon_sym_include = 28,
  anon_sym_import = 29,
  anon_sym_from = 30,
  anon_sym_macro = 31,
  anon_sym_endmacro = 32,
  anon_sym_call = 33,
  anon_sym_endcall = 34,
  anon_sym_set = 35,
  anon_sym_endset = 36,
  anon_sym_filter = 37,
  anon_sym_endfilter = 38,
  anon_sym_raw = 39,
  anon_sym_endraw = 40,
  anon_sym_with = 41,
  anon_sym_endwith = 42,
  anon_sym_autoescape = 43,
  anon_sym_endautoescape = 44,
  anon_sym_trans = 45,
  anon_sym_endtrans = 46,
  anon_sym_do = 47,
  anon_sym_debug = 48,
  anon_sym_pluralize = 49,
  sym_white_space_control = 50,
  sym__white_space = 51,
  sym_operator = 52,
  aux_sym_string_token1 = 53,
  aux_sym_string_token2 = 54,
  sym_source_file = 55,
  sym__text = 56,
  sym__not = 57,
  sym__node = 58,
  sym_statement = 59,
  sym_statement_begin = 60,
  sym_statement_end = 61,
  sym_statement_content = 62,
  sym_expression = 63,
  sym_object = 64,
  sym__object_begin = 65,
  sym__object_end = 66,
  sym_comment = 67,
  sym_keyword = 68,
  aux_sym__inner_text = 69,
  aux_sym__inner_text2 = 70,
  sym_string = 71,
  aux_sym_source_file_repeat1 = 72,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym__text_token1] = "_text_token1",
  [aux_sym__not_token1] = "_not_token1",
  [aux_sym__not_token2] = "_not_token2",
  [aux_sym__not_token3] = "_not_token3",
  [aux_sym__not_token4] = "_not_token4",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [sym_expression_begin] = "expression_begin",
  [sym_expression_end] = "expression_end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACE_POUND] = "{#",
  [aux_sym_comment_token1] = "comment_content",
  [anon_sym_POUND_RBRACE] = "#}",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_elif] = "elif",
  [anon_sym_endif] = "endif",
  [anon_sym_for] = "for",
  [anon_sym_endfor] = "endfor",
  [anon_sym_in] = "in",
  [anon_sym_while] = "while",
  [anon_sym_endwhile] = "endwhile",
  [anon_sym_block] = "block",
  [anon_sym_endblock] = "endblock",
  [anon_sym_extends] = "extends",
  [anon_sym_include] = "include",
  [anon_sym_import] = "import",
  [anon_sym_from] = "from",
  [anon_sym_macro] = "macro",
  [anon_sym_endmacro] = "endmacro",
  [anon_sym_call] = "call",
  [anon_sym_endcall] = "endcall",
  [anon_sym_set] = "set",
  [anon_sym_endset] = "endset",
  [anon_sym_filter] = "filter",
  [anon_sym_endfilter] = "endfilter",
  [anon_sym_raw] = "raw",
  [anon_sym_endraw] = "endraw",
  [anon_sym_with] = "with",
  [anon_sym_endwith] = "endwith",
  [anon_sym_autoescape] = "autoescape",
  [anon_sym_endautoescape] = "endautoescape",
  [anon_sym_trans] = "trans",
  [anon_sym_endtrans] = "endtrans",
  [anon_sym_do] = "do",
  [anon_sym_debug] = "debug",
  [anon_sym_pluralize] = "pluralize",
  [sym_white_space_control] = "white_space_control",
  [sym__white_space] = "_white_space",
  [sym_operator] = "operator",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_source_file] = "source_file",
  [sym__text] = "_text",
  [sym__not] = "_not",
  [sym__node] = "_node",
  [sym_statement] = "statement",
  [sym_statement_begin] = "statement_begin",
  [sym_statement_end] = "statement_end",
  [sym_statement_content] = "statement_content",
  [sym_expression] = "expression",
  [sym_object] = "object",
  [sym__object_begin] = "_object_begin",
  [sym__object_end] = "_object_end",
  [sym_comment] = "comment",
  [sym_keyword] = "keyword",
  [aux_sym__inner_text] = "_inner_text",
  [aux_sym__inner_text2] = "_inner_text2",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym__text_token1] = aux_sym__text_token1,
  [aux_sym__not_token1] = aux_sym__not_token1,
  [aux_sym__not_token2] = aux_sym__not_token2,
  [aux_sym__not_token3] = aux_sym__not_token3,
  [aux_sym__not_token4] = aux_sym__not_token4,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [sym_expression_begin] = sym_expression_begin,
  [sym_expression_end] = sym_expression_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_POUND_RBRACE] = anon_sym_POUND_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_endif] = anon_sym_endif,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_endfor] = anon_sym_endfor,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_endwhile] = anon_sym_endwhile,
  [anon_sym_block] = anon_sym_block,
  [anon_sym_endblock] = anon_sym_endblock,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_macro] = anon_sym_macro,
  [anon_sym_endmacro] = anon_sym_endmacro,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_endcall] = anon_sym_endcall,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_endset] = anon_sym_endset,
  [anon_sym_filter] = anon_sym_filter,
  [anon_sym_endfilter] = anon_sym_endfilter,
  [anon_sym_raw] = anon_sym_raw,
  [anon_sym_endraw] = anon_sym_endraw,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_endwith] = anon_sym_endwith,
  [anon_sym_autoescape] = anon_sym_autoescape,
  [anon_sym_endautoescape] = anon_sym_endautoescape,
  [anon_sym_trans] = anon_sym_trans,
  [anon_sym_endtrans] = anon_sym_endtrans,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_debug] = anon_sym_debug,
  [anon_sym_pluralize] = anon_sym_pluralize,
  [sym_white_space_control] = sym_white_space_control,
  [sym__white_space] = sym__white_space,
  [sym_operator] = sym_operator,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_source_file] = sym_source_file,
  [sym__text] = sym__text,
  [sym__not] = sym__not,
  [sym__node] = sym__node,
  [sym_statement] = sym_statement,
  [sym_statement_begin] = sym_statement_begin,
  [sym_statement_end] = sym_statement_end,
  [sym_statement_content] = sym_statement_content,
  [sym_expression] = sym_expression,
  [sym_object] = sym_object,
  [sym__object_begin] = sym__object_begin,
  [sym__object_end] = sym__object_end,
  [sym_comment] = sym_comment,
  [sym_keyword] = sym_keyword,
  [aux_sym__inner_text] = aux_sym__inner_text,
  [aux_sym__inner_text2] = aux_sym__inner_text2,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__text_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__not_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__not_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__not_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__not_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_expression_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endfor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endwhile] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endblock] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_macro] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endmacro] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endcall] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_filter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endfilter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_raw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endraw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endwith] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_autoescape] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endautoescape] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trans] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endtrans] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_debug] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pluralize] = {
    .visible = true,
    .named = false,
  },
  [sym_white_space_control] = {
    .visible = true,
    .named = true,
  },
  [sym__white_space] = {
    .visible = false,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__not] = {
    .visible = false,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_end] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_content] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym__object_begin] = {
    .visible = false,
    .named = true,
  },
  [sym__object_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inner_text] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__inner_text2] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_identifier = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_identifier] = "identifier",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_identifier, 0},
  [1] =
    {field_identifier, 1, .inherited = true},
  [2] =
    {field_identifier, 0, .inherited = true},
    {field_identifier, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 15,
  [19] = 17,
  [20] = 17,
  [21] = 21,
  [22] = 21,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 8,
  [32] = 32,
  [33] = 9,
  [34] = 32,
  [35] = 6,
  [36] = 6,
  [37] = 8,
  [38] = 9,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
};

const TSCharacterRange sym_operator_character_set_1[] = {
  {0, '!'}, {'$', '$'}, {'&', '&'}, {'(', '/'}, {':', '@'}, {'[', '^'}, {'`', '`'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '%') ADVANCE(7);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '%') ADVANCE(10);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '{') ADVANCE(34);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '}') ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '{') ADVANCE(34);
      if (lookahead == '}') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '%') ADVANCE(48);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '{') ADVANCE(34);
      if (lookahead == '}') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '%') ADVANCE(48);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(50);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '%') ADVANCE(7);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '}') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '%') ADVANCE(10);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(49);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(33);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == '%') ADVANCE(28);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '}') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '%') ADVANCE(29);
      if (lookahead == '}') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(15);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym__not_token1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym__not_token1);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '%') ADVANCE(30);
      if (lookahead == '{') ADVANCE(32);
      if (lookahead == '}') ADVANCE(18);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__not_token2);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__not_token2);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '%') ADVANCE(29);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym__not_token3);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__not_token3);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '%') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__not_token3);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__not_token3);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__not_token3);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__not_token4);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__not_token4);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '%') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__not_token4);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_expression_begin);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_expression_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '%') ADVANCE(30);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '#') ADVANCE(25);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_POUND_RBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_white_space_control);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_white_space_control);
      if (lookahead == '#') ADVANCE(25);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_white_space_control);
      if ((!eof && set_contains(sym_operator_character_set_1, 9, lookahead))) ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__white_space);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '#') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_operator);
      if ((!eof && set_contains(sym_operator_character_set_1, 9, lookahead))) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'i', 7,
        'm', 8,
        'p', 9,
        'r', 10,
        's', 11,
        't', 12,
        'w', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 'x') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(23);
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(25);
      if (lookahead == 'm') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(33);
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 17:
      if (lookahead == 'b') ADVANCE(38);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(39);
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(41);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(46);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 28:
      if (lookahead == 'c') ADVANCE(48);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 30:
      if (lookahead == 'w') ADVANCE(50);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 33:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(55);
      END_STATE();
    case 36:
      if (lookahead == 'c') ADVANCE(56);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(57);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(58);
      END_STATE();
    case 39:
      if (lookahead == 'f') ADVANCE(59);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 41:
      ADVANCE_MAP(
        'a', 61,
        'b', 62,
        'c', 63,
        'f', 64,
        'i', 65,
        'm', 66,
        'r', 67,
        's', 68,
        't', 69,
        'w', 70,
      );
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 45:
      if (lookahead == 'm') ADVANCE(73);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(74);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(75);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(76);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(77);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_raw);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(78);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(79);
      END_STATE();
    case 54:
      if (lookahead == 'h') ADVANCE(80);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 56:
      if (lookahead == 'k') ADVANCE(82);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 58:
      if (lookahead == 'g') ADVANCE(83);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 61:
      if (lookahead == 'u') ADVANCE(84);
      END_STATE();
    case 62:
      if (lookahead == 'l') ADVANCE(85);
      END_STATE();
    case 63:
      if (lookahead == 'a') ADVANCE(86);
      END_STATE();
    case 64:
      if (lookahead == 'i') ADVANCE(87);
      if (lookahead == 'o') ADVANCE(88);
      END_STATE();
    case 65:
      if (lookahead == 'f') ADVANCE(89);
      END_STATE();
    case 66:
      if (lookahead == 'a') ADVANCE(90);
      END_STATE();
    case 67:
      if (lookahead == 'a') ADVANCE(91);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 69:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 70:
      if (lookahead == 'h') ADVANCE(94);
      if (lookahead == 'i') ADVANCE(95);
      END_STATE();
    case 71:
      if (lookahead == 'n') ADVANCE(96);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 74:
      if (lookahead == 'r') ADVANCE(98);
      END_STATE();
    case 75:
      if (lookahead == 'u') ADVANCE(99);
      END_STATE();
    case 76:
      if (lookahead == 'o') ADVANCE(100);
      END_STATE();
    case 77:
      if (lookahead == 'a') ADVANCE(101);
      END_STATE();
    case 78:
      if (lookahead == 's') ADVANCE(102);
      END_STATE();
    case 79:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 81:
      if (lookahead == 's') ADVANCE(104);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_block);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_debug);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(105);
      END_STATE();
    case 85:
      if (lookahead == 'o') ADVANCE(106);
      END_STATE();
    case 86:
      if (lookahead == 'l') ADVANCE(107);
      END_STATE();
    case 87:
      if (lookahead == 'l') ADVANCE(108);
      END_STATE();
    case 88:
      if (lookahead == 'r') ADVANCE(109);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_endif);
      END_STATE();
    case 90:
      if (lookahead == 'c') ADVANCE(110);
      END_STATE();
    case 91:
      if (lookahead == 'w') ADVANCE(111);
      END_STATE();
    case 92:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 93:
      if (lookahead == 'a') ADVANCE(113);
      END_STATE();
    case 94:
      if (lookahead == 'i') ADVANCE(114);
      END_STATE();
    case 95:
      if (lookahead == 't') ADVANCE(115);
      END_STATE();
    case 96:
      if (lookahead == 'd') ADVANCE(116);
      END_STATE();
    case 97:
      if (lookahead == 'r') ADVANCE(117);
      END_STATE();
    case 98:
      if (lookahead == 't') ADVANCE(118);
      END_STATE();
    case 99:
      if (lookahead == 'd') ADVANCE(119);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_macro);
      END_STATE();
    case 101:
      if (lookahead == 'l') ADVANCE(120);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_trans);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 104:
      if (lookahead == 'c') ADVANCE(121);
      END_STATE();
    case 105:
      if (lookahead == 'o') ADVANCE(122);
      END_STATE();
    case 106:
      if (lookahead == 'c') ADVANCE(123);
      END_STATE();
    case 107:
      if (lookahead == 'l') ADVANCE(124);
      END_STATE();
    case 108:
      if (lookahead == 't') ADVANCE(125);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_endfor);
      END_STATE();
    case 110:
      if (lookahead == 'r') ADVANCE(126);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_endraw);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_endset);
      END_STATE();
    case 113:
      if (lookahead == 'n') ADVANCE(127);
      END_STATE();
    case 114:
      if (lookahead == 'l') ADVANCE(128);
      END_STATE();
    case 115:
      if (lookahead == 'h') ADVANCE(129);
      END_STATE();
    case 116:
      if (lookahead == 's') ADVANCE(130);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_filter);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 119:
      if (lookahead == 'e') ADVANCE(131);
      END_STATE();
    case 120:
      if (lookahead == 'i') ADVANCE(132);
      END_STATE();
    case 121:
      if (lookahead == 'a') ADVANCE(133);
      END_STATE();
    case 122:
      if (lookahead == 'e') ADVANCE(134);
      END_STATE();
    case 123:
      if (lookahead == 'k') ADVANCE(135);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_endcall);
      END_STATE();
    case 125:
      if (lookahead == 'e') ADVANCE(136);
      END_STATE();
    case 126:
      if (lookahead == 'o') ADVANCE(137);
      END_STATE();
    case 127:
      if (lookahead == 's') ADVANCE(138);
      END_STATE();
    case 128:
      if (lookahead == 'e') ADVANCE(139);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_endwith);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 132:
      if (lookahead == 'z') ADVANCE(140);
      END_STATE();
    case 133:
      if (lookahead == 'p') ADVANCE(141);
      END_STATE();
    case 134:
      if (lookahead == 's') ADVANCE(142);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_endblock);
      END_STATE();
    case 136:
      if (lookahead == 'r') ADVANCE(143);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_endmacro);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_endtrans);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_endwhile);
      END_STATE();
    case 140:
      if (lookahead == 'e') ADVANCE(144);
      END_STATE();
    case 141:
      if (lookahead == 'e') ADVANCE(145);
      END_STATE();
    case 142:
      if (lookahead == 'c') ADVANCE(146);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_endfilter);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_pluralize);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_autoescape);
      END_STATE();
    case 146:
      if (lookahead == 'a') ADVANCE(147);
      END_STATE();
    case 147:
      if (lookahead == 'p') ADVANCE(148);
      END_STATE();
    case 148:
      if (lookahead == 'e') ADVANCE(149);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_endautoescape);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 13},
  [14] = {.lex_state = 13},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 13},
  [26] = {.lex_state = 13},
  [27] = {.lex_state = 13},
  [28] = {.lex_state = 13},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 39},
  [43] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym__not_token3] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_endfor] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_endwhile] = ACTIONS(1),
    [anon_sym_block] = ACTIONS(1),
    [anon_sym_endblock] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_macro] = ACTIONS(1),
    [anon_sym_endmacro] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_endcall] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_endset] = ACTIONS(1),
    [anon_sym_filter] = ACTIONS(1),
    [anon_sym_endfilter] = ACTIONS(1),
    [anon_sym_raw] = ACTIONS(1),
    [anon_sym_endraw] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_endwith] = ACTIONS(1),
    [anon_sym_autoescape] = ACTIONS(1),
    [anon_sym_endautoescape] = ACTIONS(1),
    [anon_sym_trans] = ACTIONS(1),
    [anon_sym_endtrans] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_debug] = ACTIONS(1),
    [anon_sym_pluralize] = ACTIONS(1),
    [sym_white_space_control] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(41),
    [sym__text] = STATE(13),
    [sym__not] = STATE(13),
    [sym__node] = STATE(13),
    [sym_statement] = STATE(13),
    [sym_statement_begin] = STATE(10),
    [sym_expression] = STATE(13),
    [sym_comment] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym__text_token1] = ACTIONS(5),
    [aux_sym__not_token1] = ACTIONS(5),
    [aux_sym__not_token2] = ACTIONS(5),
    [aux_sym__not_token3] = ACTIONS(5),
    [aux_sym__not_token4] = ACTIONS(5),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(7),
    [sym_expression_begin] = ACTIONS(9),
    [anon_sym_LBRACE_POUND] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_object] = STATE(2),
    [sym__object_begin] = STATE(20),
    [sym_keyword] = STATE(2),
    [aux_sym__inner_text] = STATE(2),
    [sym_string] = STATE(2),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(16),
    [anon_sym_LBRACE] = ACTIONS(18),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_else] = ACTIONS(21),
    [anon_sym_elif] = ACTIONS(21),
    [anon_sym_endif] = ACTIONS(21),
    [anon_sym_for] = ACTIONS(21),
    [anon_sym_endfor] = ACTIONS(21),
    [anon_sym_in] = ACTIONS(21),
    [anon_sym_while] = ACTIONS(21),
    [anon_sym_endwhile] = ACTIONS(21),
    [anon_sym_block] = ACTIONS(21),
    [anon_sym_endblock] = ACTIONS(21),
    [anon_sym_extends] = ACTIONS(21),
    [anon_sym_include] = ACTIONS(21),
    [anon_sym_import] = ACTIONS(21),
    [anon_sym_from] = ACTIONS(21),
    [anon_sym_macro] = ACTIONS(21),
    [anon_sym_endmacro] = ACTIONS(21),
    [anon_sym_call] = ACTIONS(21),
    [anon_sym_endcall] = ACTIONS(21),
    [anon_sym_set] = ACTIONS(21),
    [anon_sym_endset] = ACTIONS(21),
    [anon_sym_filter] = ACTIONS(21),
    [anon_sym_endfilter] = ACTIONS(21),
    [anon_sym_raw] = ACTIONS(21),
    [anon_sym_endraw] = ACTIONS(21),
    [anon_sym_with] = ACTIONS(21),
    [anon_sym_endwith] = ACTIONS(21),
    [anon_sym_autoescape] = ACTIONS(21),
    [anon_sym_endautoescape] = ACTIONS(21),
    [anon_sym_trans] = ACTIONS(21),
    [anon_sym_endtrans] = ACTIONS(21),
    [anon_sym_do] = ACTIONS(21),
    [anon_sym_debug] = ACTIONS(21),
    [anon_sym_pluralize] = ACTIONS(21),
    [sym_white_space_control] = ACTIONS(16),
    [sym__white_space] = ACTIONS(24),
    [sym_operator] = ACTIONS(24),
    [aux_sym_string_token1] = ACTIONS(27),
    [aux_sym_string_token2] = ACTIONS(27),
  },
  [STATE(3)] = {
    [sym_object] = STATE(4),
    [sym__object_begin] = STATE(20),
    [sym_keyword] = STATE(4),
    [aux_sym__inner_text] = STATE(4),
    [sym_string] = STATE(4),
    [sym_identifier] = ACTIONS(30),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(32),
    [anon_sym_LBRACE] = ACTIONS(34),
    [anon_sym_if] = ACTIONS(36),
    [anon_sym_else] = ACTIONS(36),
    [anon_sym_elif] = ACTIONS(36),
    [anon_sym_endif] = ACTIONS(36),
    [anon_sym_for] = ACTIONS(36),
    [anon_sym_endfor] = ACTIONS(36),
    [anon_sym_in] = ACTIONS(36),
    [anon_sym_while] = ACTIONS(36),
    [anon_sym_endwhile] = ACTIONS(36),
    [anon_sym_block] = ACTIONS(36),
    [anon_sym_endblock] = ACTIONS(36),
    [anon_sym_extends] = ACTIONS(36),
    [anon_sym_include] = ACTIONS(36),
    [anon_sym_import] = ACTIONS(36),
    [anon_sym_from] = ACTIONS(36),
    [anon_sym_macro] = ACTIONS(36),
    [anon_sym_endmacro] = ACTIONS(36),
    [anon_sym_call] = ACTIONS(36),
    [anon_sym_endcall] = ACTIONS(36),
    [anon_sym_set] = ACTIONS(36),
    [anon_sym_endset] = ACTIONS(36),
    [anon_sym_filter] = ACTIONS(36),
    [anon_sym_endfilter] = ACTIONS(36),
    [anon_sym_raw] = ACTIONS(36),
    [anon_sym_endraw] = ACTIONS(36),
    [anon_sym_with] = ACTIONS(36),
    [anon_sym_endwith] = ACTIONS(36),
    [anon_sym_autoescape] = ACTIONS(36),
    [anon_sym_endautoescape] = ACTIONS(36),
    [anon_sym_trans] = ACTIONS(36),
    [anon_sym_endtrans] = ACTIONS(36),
    [anon_sym_do] = ACTIONS(36),
    [anon_sym_debug] = ACTIONS(36),
    [anon_sym_pluralize] = ACTIONS(36),
    [sym_white_space_control] = ACTIONS(32),
    [sym__white_space] = ACTIONS(38),
    [sym_operator] = ACTIONS(38),
    [aux_sym_string_token1] = ACTIONS(40),
    [aux_sym_string_token2] = ACTIONS(40),
  },
  [STATE(4)] = {
    [sym_object] = STATE(2),
    [sym__object_begin] = STATE(20),
    [sym_keyword] = STATE(2),
    [aux_sym__inner_text] = STATE(2),
    [sym_string] = STATE(2),
    [sym_identifier] = ACTIONS(30),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(42),
    [anon_sym_LBRACE] = ACTIONS(34),
    [anon_sym_if] = ACTIONS(36),
    [anon_sym_else] = ACTIONS(36),
    [anon_sym_elif] = ACTIONS(36),
    [anon_sym_endif] = ACTIONS(36),
    [anon_sym_for] = ACTIONS(36),
    [anon_sym_endfor] = ACTIONS(36),
    [anon_sym_in] = ACTIONS(36),
    [anon_sym_while] = ACTIONS(36),
    [anon_sym_endwhile] = ACTIONS(36),
    [anon_sym_block] = ACTIONS(36),
    [anon_sym_endblock] = ACTIONS(36),
    [anon_sym_extends] = ACTIONS(36),
    [anon_sym_include] = ACTIONS(36),
    [anon_sym_import] = ACTIONS(36),
    [anon_sym_from] = ACTIONS(36),
    [anon_sym_macro] = ACTIONS(36),
    [anon_sym_endmacro] = ACTIONS(36),
    [anon_sym_call] = ACTIONS(36),
    [anon_sym_endcall] = ACTIONS(36),
    [anon_sym_set] = ACTIONS(36),
    [anon_sym_endset] = ACTIONS(36),
    [anon_sym_filter] = ACTIONS(36),
    [anon_sym_endfilter] = ACTIONS(36),
    [anon_sym_raw] = ACTIONS(36),
    [anon_sym_endraw] = ACTIONS(36),
    [anon_sym_with] = ACTIONS(36),
    [anon_sym_endwith] = ACTIONS(36),
    [anon_sym_autoescape] = ACTIONS(36),
    [anon_sym_endautoescape] = ACTIONS(36),
    [anon_sym_trans] = ACTIONS(36),
    [anon_sym_endtrans] = ACTIONS(36),
    [anon_sym_do] = ACTIONS(36),
    [anon_sym_debug] = ACTIONS(36),
    [anon_sym_pluralize] = ACTIONS(36),
    [sym_white_space_control] = ACTIONS(42),
    [sym__white_space] = ACTIONS(44),
    [sym_operator] = ACTIONS(44),
    [aux_sym_string_token1] = ACTIONS(40),
    [aux_sym_string_token2] = ACTIONS(40),
  },
  [STATE(5)] = {
    [sym_identifier] = ACTIONS(46),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(46),
    [anon_sym_LBRACE] = ACTIONS(46),
    [anon_sym_if] = ACTIONS(46),
    [anon_sym_else] = ACTIONS(46),
    [anon_sym_elif] = ACTIONS(46),
    [anon_sym_endif] = ACTIONS(46),
    [anon_sym_for] = ACTIONS(46),
    [anon_sym_endfor] = ACTIONS(46),
    [anon_sym_in] = ACTIONS(46),
    [anon_sym_while] = ACTIONS(46),
    [anon_sym_endwhile] = ACTIONS(46),
    [anon_sym_block] = ACTIONS(46),
    [anon_sym_endblock] = ACTIONS(46),
    [anon_sym_extends] = ACTIONS(46),
    [anon_sym_include] = ACTIONS(46),
    [anon_sym_import] = ACTIONS(46),
    [anon_sym_from] = ACTIONS(46),
    [anon_sym_macro] = ACTIONS(46),
    [anon_sym_endmacro] = ACTIONS(46),
    [anon_sym_call] = ACTIONS(46),
    [anon_sym_endcall] = ACTIONS(46),
    [anon_sym_set] = ACTIONS(46),
    [anon_sym_endset] = ACTIONS(46),
    [anon_sym_filter] = ACTIONS(46),
    [anon_sym_endfilter] = ACTIONS(46),
    [anon_sym_raw] = ACTIONS(46),
    [anon_sym_endraw] = ACTIONS(46),
    [anon_sym_with] = ACTIONS(46),
    [anon_sym_endwith] = ACTIONS(46),
    [anon_sym_autoescape] = ACTIONS(46),
    [anon_sym_endautoescape] = ACTIONS(46),
    [anon_sym_trans] = ACTIONS(46),
    [anon_sym_endtrans] = ACTIONS(46),
    [anon_sym_do] = ACTIONS(46),
    [anon_sym_debug] = ACTIONS(46),
    [anon_sym_pluralize] = ACTIONS(46),
    [sym_white_space_control] = ACTIONS(46),
    [sym__white_space] = ACTIONS(46),
    [sym_operator] = ACTIONS(46),
    [aux_sym_string_token1] = ACTIONS(46),
    [aux_sym_string_token2] = ACTIONS(46),
  },
  [STATE(6)] = {
    [sym_identifier] = ACTIONS(48),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(48),
    [anon_sym_LBRACE] = ACTIONS(48),
    [anon_sym_if] = ACTIONS(48),
    [anon_sym_else] = ACTIONS(48),
    [anon_sym_elif] = ACTIONS(48),
    [anon_sym_endif] = ACTIONS(48),
    [anon_sym_for] = ACTIONS(48),
    [anon_sym_endfor] = ACTIONS(48),
    [anon_sym_in] = ACTIONS(48),
    [anon_sym_while] = ACTIONS(48),
    [anon_sym_endwhile] = ACTIONS(48),
    [anon_sym_block] = ACTIONS(48),
    [anon_sym_endblock] = ACTIONS(48),
    [anon_sym_extends] = ACTIONS(48),
    [anon_sym_include] = ACTIONS(48),
    [anon_sym_import] = ACTIONS(48),
    [anon_sym_from] = ACTIONS(48),
    [anon_sym_macro] = ACTIONS(48),
    [anon_sym_endmacro] = ACTIONS(48),
    [anon_sym_call] = ACTIONS(48),
    [anon_sym_endcall] = ACTIONS(48),
    [anon_sym_set] = ACTIONS(48),
    [anon_sym_endset] = ACTIONS(48),
    [anon_sym_filter] = ACTIONS(48),
    [anon_sym_endfilter] = ACTIONS(48),
    [anon_sym_raw] = ACTIONS(48),
    [anon_sym_endraw] = ACTIONS(48),
    [anon_sym_with] = ACTIONS(48),
    [anon_sym_endwith] = ACTIONS(48),
    [anon_sym_autoescape] = ACTIONS(48),
    [anon_sym_endautoescape] = ACTIONS(48),
    [anon_sym_trans] = ACTIONS(48),
    [anon_sym_endtrans] = ACTIONS(48),
    [anon_sym_do] = ACTIONS(48),
    [anon_sym_debug] = ACTIONS(48),
    [anon_sym_pluralize] = ACTIONS(48),
    [sym_white_space_control] = ACTIONS(48),
    [sym__white_space] = ACTIONS(48),
    [sym_operator] = ACTIONS(48),
    [aux_sym_string_token1] = ACTIONS(48),
    [aux_sym_string_token2] = ACTIONS(48),
  },
  [STATE(7)] = {
    [sym_identifier] = ACTIONS(50),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(50),
    [anon_sym_if] = ACTIONS(50),
    [anon_sym_else] = ACTIONS(50),
    [anon_sym_elif] = ACTIONS(50),
    [anon_sym_endif] = ACTIONS(50),
    [anon_sym_for] = ACTIONS(50),
    [anon_sym_endfor] = ACTIONS(50),
    [anon_sym_in] = ACTIONS(50),
    [anon_sym_while] = ACTIONS(50),
    [anon_sym_endwhile] = ACTIONS(50),
    [anon_sym_block] = ACTIONS(50),
    [anon_sym_endblock] = ACTIONS(50),
    [anon_sym_extends] = ACTIONS(50),
    [anon_sym_include] = ACTIONS(50),
    [anon_sym_import] = ACTIONS(50),
    [anon_sym_from] = ACTIONS(50),
    [anon_sym_macro] = ACTIONS(50),
    [anon_sym_endmacro] = ACTIONS(50),
    [anon_sym_call] = ACTIONS(50),
    [anon_sym_endcall] = ACTIONS(50),
    [anon_sym_set] = ACTIONS(50),
    [anon_sym_endset] = ACTIONS(50),
    [anon_sym_filter] = ACTIONS(50),
    [anon_sym_endfilter] = ACTIONS(50),
    [anon_sym_raw] = ACTIONS(50),
    [anon_sym_endraw] = ACTIONS(50),
    [anon_sym_with] = ACTIONS(50),
    [anon_sym_endwith] = ACTIONS(50),
    [anon_sym_autoescape] = ACTIONS(50),
    [anon_sym_endautoescape] = ACTIONS(50),
    [anon_sym_trans] = ACTIONS(50),
    [anon_sym_endtrans] = ACTIONS(50),
    [anon_sym_do] = ACTIONS(50),
    [anon_sym_debug] = ACTIONS(50),
    [anon_sym_pluralize] = ACTIONS(50),
    [sym_white_space_control] = ACTIONS(50),
    [sym__white_space] = ACTIONS(50),
    [sym_operator] = ACTIONS(50),
    [aux_sym_string_token1] = ACTIONS(50),
    [aux_sym_string_token2] = ACTIONS(50),
  },
  [STATE(8)] = {
    [sym_identifier] = ACTIONS(52),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(52),
    [anon_sym_LBRACE] = ACTIONS(52),
    [anon_sym_if] = ACTIONS(52),
    [anon_sym_else] = ACTIONS(52),
    [anon_sym_elif] = ACTIONS(52),
    [anon_sym_endif] = ACTIONS(52),
    [anon_sym_for] = ACTIONS(52),
    [anon_sym_endfor] = ACTIONS(52),
    [anon_sym_in] = ACTIONS(52),
    [anon_sym_while] = ACTIONS(52),
    [anon_sym_endwhile] = ACTIONS(52),
    [anon_sym_block] = ACTIONS(52),
    [anon_sym_endblock] = ACTIONS(52),
    [anon_sym_extends] = ACTIONS(52),
    [anon_sym_include] = ACTIONS(52),
    [anon_sym_import] = ACTIONS(52),
    [anon_sym_from] = ACTIONS(52),
    [anon_sym_macro] = ACTIONS(52),
    [anon_sym_endmacro] = ACTIONS(52),
    [anon_sym_call] = ACTIONS(52),
    [anon_sym_endcall] = ACTIONS(52),
    [anon_sym_set] = ACTIONS(52),
    [anon_sym_endset] = ACTIONS(52),
    [anon_sym_filter] = ACTIONS(52),
    [anon_sym_endfilter] = ACTIONS(52),
    [anon_sym_raw] = ACTIONS(52),
    [anon_sym_endraw] = ACTIONS(52),
    [anon_sym_with] = ACTIONS(52),
    [anon_sym_endwith] = ACTIONS(52),
    [anon_sym_autoescape] = ACTIONS(52),
    [anon_sym_endautoescape] = ACTIONS(52),
    [anon_sym_trans] = ACTIONS(52),
    [anon_sym_endtrans] = ACTIONS(52),
    [anon_sym_do] = ACTIONS(52),
    [anon_sym_debug] = ACTIONS(52),
    [anon_sym_pluralize] = ACTIONS(52),
    [sym_white_space_control] = ACTIONS(52),
    [sym__white_space] = ACTIONS(52),
    [sym_operator] = ACTIONS(52),
    [aux_sym_string_token1] = ACTIONS(52),
    [aux_sym_string_token2] = ACTIONS(52),
  },
  [STATE(9)] = {
    [sym_identifier] = ACTIONS(54),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(54),
    [anon_sym_LBRACE] = ACTIONS(54),
    [anon_sym_if] = ACTIONS(54),
    [anon_sym_else] = ACTIONS(54),
    [anon_sym_elif] = ACTIONS(54),
    [anon_sym_endif] = ACTIONS(54),
    [anon_sym_for] = ACTIONS(54),
    [anon_sym_endfor] = ACTIONS(54),
    [anon_sym_in] = ACTIONS(54),
    [anon_sym_while] = ACTIONS(54),
    [anon_sym_endwhile] = ACTIONS(54),
    [anon_sym_block] = ACTIONS(54),
    [anon_sym_endblock] = ACTIONS(54),
    [anon_sym_extends] = ACTIONS(54),
    [anon_sym_include] = ACTIONS(54),
    [anon_sym_import] = ACTIONS(54),
    [anon_sym_from] = ACTIONS(54),
    [anon_sym_macro] = ACTIONS(54),
    [anon_sym_endmacro] = ACTIONS(54),
    [anon_sym_call] = ACTIONS(54),
    [anon_sym_endcall] = ACTIONS(54),
    [anon_sym_set] = ACTIONS(54),
    [anon_sym_endset] = ACTIONS(54),
    [anon_sym_filter] = ACTIONS(54),
    [anon_sym_endfilter] = ACTIONS(54),
    [anon_sym_raw] = ACTIONS(54),
    [anon_sym_endraw] = ACTIONS(54),
    [anon_sym_with] = ACTIONS(54),
    [anon_sym_endwith] = ACTIONS(54),
    [anon_sym_autoescape] = ACTIONS(54),
    [anon_sym_endautoescape] = ACTIONS(54),
    [anon_sym_trans] = ACTIONS(54),
    [anon_sym_endtrans] = ACTIONS(54),
    [anon_sym_do] = ACTIONS(54),
    [anon_sym_debug] = ACTIONS(54),
    [anon_sym_pluralize] = ACTIONS(54),
    [sym_white_space_control] = ACTIONS(54),
    [sym__white_space] = ACTIONS(54),
    [sym_operator] = ACTIONS(54),
    [aux_sym_string_token1] = ACTIONS(54),
    [aux_sym_string_token2] = ACTIONS(54),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(36), 1,
      anon_sym_in,
    STATE(3), 1,
      sym_keyword,
    STATE(39), 1,
      sym_statement_content,
    ACTIONS(56), 33,
      anon_sym_if,
      anon_sym_else,
      anon_sym_elif,
      anon_sym_endif,
      anon_sym_for,
      anon_sym_endfor,
      anon_sym_while,
      anon_sym_endwhile,
      anon_sym_block,
      anon_sym_endblock,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_import,
      anon_sym_from,
      anon_sym_macro,
      anon_sym_endmacro,
      anon_sym_call,
      anon_sym_endcall,
      anon_sym_set,
      anon_sym_endset,
      anon_sym_filter,
      anon_sym_endfilter,
      anon_sym_raw,
      anon_sym_endraw,
      anon_sym_with,
      anon_sym_endwith,
      anon_sym_autoescape,
      anon_sym_endautoescape,
      anon_sym_trans,
      anon_sym_endtrans,
      anon_sym_do,
      anon_sym_debug,
      anon_sym_pluralize,
  [45] = 3,
    ACTIONS(60), 1,
      anon_sym_in,
    ACTIONS(62), 1,
      sym_white_space_control,
    ACTIONS(58), 33,
      anon_sym_if,
      anon_sym_else,
      anon_sym_elif,
      anon_sym_endif,
      anon_sym_for,
      anon_sym_endfor,
      anon_sym_while,
      anon_sym_endwhile,
      anon_sym_block,
      anon_sym_endblock,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_import,
      anon_sym_from,
      anon_sym_macro,
      anon_sym_endmacro,
      anon_sym_call,
      anon_sym_endcall,
      anon_sym_set,
      anon_sym_endset,
      anon_sym_filter,
      anon_sym_endfilter,
      anon_sym_raw,
      anon_sym_endraw,
      anon_sym_with,
      anon_sym_endwith,
      anon_sym_autoescape,
      anon_sym_endautoescape,
      anon_sym_trans,
      anon_sym_endtrans,
      anon_sym_do,
      anon_sym_debug,
      anon_sym_pluralize,
  [87] = 2,
    ACTIONS(66), 1,
      anon_sym_in,
    ACTIONS(64), 33,
      anon_sym_if,
      anon_sym_else,
      anon_sym_elif,
      anon_sym_endif,
      anon_sym_for,
      anon_sym_endfor,
      anon_sym_while,
      anon_sym_endwhile,
      anon_sym_block,
      anon_sym_endblock,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_import,
      anon_sym_from,
      anon_sym_macro,
      anon_sym_endmacro,
      anon_sym_call,
      anon_sym_endcall,
      anon_sym_set,
      anon_sym_endset,
      anon_sym_filter,
      anon_sym_endfilter,
      anon_sym_raw,
      anon_sym_endraw,
      anon_sym_with,
      anon_sym_endwith,
      anon_sym_autoescape,
      anon_sym_endautoescape,
      anon_sym_trans,
      anon_sym_endtrans,
      anon_sym_do,
      anon_sym_debug,
      anon_sym_pluralize,
  [126] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(9), 1,
      sym_expression_begin,
    ACTIONS(11), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym_statement_begin,
    ACTIONS(70), 5,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
    STATE(14), 7,
      sym__text,
      sym__not,
      sym__node,
      sym_statement,
      sym_expression,
      sym_comment,
      aux_sym_source_file_repeat1,
  [158] = 7,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(80), 1,
      sym_expression_begin,
    ACTIONS(83), 1,
      anon_sym_LBRACE_POUND,
    STATE(10), 1,
      sym_statement_begin,
    ACTIONS(74), 5,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
    STATE(14), 7,
      sym__text,
      sym__not,
      sym__node,
      sym_statement,
      sym_expression,
      sym_comment,
      aux_sym_source_file_repeat1,
  [190] = 8,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      sym__object_begin,
    STATE(38), 1,
      sym__object_end,
    ACTIONS(92), 2,
      sym__white_space,
      sym_operator,
    ACTIONS(94), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(22), 3,
      sym_object,
      aux_sym__inner_text2,
      sym_string,
  [219] = 8,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      sym__object_begin,
    STATE(33), 1,
      sym__object_end,
    ACTIONS(92), 2,
      sym__white_space,
      sym_operator,
    ACTIONS(94), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(22), 3,
      sym_object,
      aux_sym__inner_text2,
      sym_string,
  [248] = 8,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      sym__object_begin,
    STATE(37), 1,
      sym__object_end,
    ACTIONS(94), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(100), 2,
      sym__white_space,
      sym_operator,
    STATE(15), 3,
      sym_object,
      aux_sym__inner_text2,
      sym_string,
  [277] = 8,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym__object_end,
    STATE(17), 1,
      sym__object_begin,
    ACTIONS(92), 2,
      sym__white_space,
      sym_operator,
    ACTIONS(94), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(22), 3,
      sym_object,
      aux_sym__inner_text2,
      sym_string,
  [306] = 8,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      sym__object_begin,
    STATE(31), 1,
      sym__object_end,
    ACTIONS(94), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(106), 2,
      sym__white_space,
      sym_operator,
    STATE(16), 3,
      sym_object,
      aux_sym__inner_text2,
      sym_string,
  [335] = 8,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym__object_end,
    STATE(17), 1,
      sym__object_begin,
    ACTIONS(94), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(110), 2,
      sym__white_space,
      sym_operator,
    STATE(18), 3,
      sym_object,
      aux_sym__inner_text2,
      sym_string,
  [364] = 7,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(115), 1,
      sym_expression_end,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym__object_begin,
    ACTIONS(120), 2,
      sym__white_space,
      sym_operator,
    ACTIONS(123), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(21), 3,
      sym_object,
      aux_sym__inner_text2,
      sym_string,
  [390] = 7,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym__object_begin,
    ACTIONS(132), 2,
      sym__white_space,
      sym_operator,
    ACTIONS(135), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(22), 3,
      sym_object,
      aux_sym__inner_text2,
      sym_string,
  [416] = 7,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(140), 1,
      sym_expression_end,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym__object_begin,
    ACTIONS(144), 2,
      sym__white_space,
      sym_operator,
    ACTIONS(146), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(24), 3,
      sym_object,
      aux_sym__inner_text2,
      sym_string,
  [442] = 7,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      sym_expression_end,
    STATE(19), 1,
      sym__object_begin,
    ACTIONS(146), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(150), 2,
      sym__white_space,
      sym_operator,
    STATE(21), 3,
      sym_object,
      aux_sym__inner_text2,
      sym_string,
  [468] = 2,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(154), 8,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
      anon_sym_LBRACE_PERCENT,
      sym_expression_begin,
      anon_sym_LBRACE_POUND,
  [482] = 2,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 8,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
      anon_sym_LBRACE_PERCENT,
      sym_expression_begin,
      anon_sym_LBRACE_POUND,
  [496] = 2,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
    ACTIONS(162), 8,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
      anon_sym_LBRACE_PERCENT,
      sym_expression_begin,
      anon_sym_LBRACE_POUND,
  [510] = 2,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
    ACTIONS(166), 8,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
      anon_sym_LBRACE_PERCENT,
      sym_expression_begin,
      anon_sym_LBRACE_POUND,
  [524] = 2,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(170), 8,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
      anon_sym_LBRACE_PERCENT,
      sym_expression_begin,
      anon_sym_LBRACE_POUND,
  [538] = 2,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    ACTIONS(174), 8,
      aux_sym__text_token1,
      aux_sym__not_token1,
      aux_sym__not_token2,
      aux_sym__not_token3,
      aux_sym__not_token4,
      anon_sym_LBRACE_PERCENT,
      sym_expression_begin,
      anon_sym_LBRACE_POUND,
  [552] = 1,
    ACTIONS(52), 7,
      sym_expression_end,
      anon_sym_LBRACE,
      sym__white_space,
      sym_identifier,
      sym_operator,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [562] = 1,
    ACTIONS(176), 7,
      sym_expression_end,
      anon_sym_LBRACE,
      sym__white_space,
      sym_identifier,
      sym_operator,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [572] = 1,
    ACTIONS(54), 7,
      sym_expression_end,
      anon_sym_LBRACE,
      sym__white_space,
      sym_identifier,
      sym_operator,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [582] = 1,
    ACTIONS(176), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__white_space,
      sym_identifier,
      sym_operator,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [592] = 1,
    ACTIONS(48), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__white_space,
      sym_identifier,
      sym_operator,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [602] = 1,
    ACTIONS(48), 7,
      sym_expression_end,
      anon_sym_LBRACE,
      sym__white_space,
      sym_identifier,
      sym_operator,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [612] = 1,
    ACTIONS(52), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__white_space,
      sym_identifier,
      sym_operator,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [622] = 1,
    ACTIONS(54), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__white_space,
      sym_identifier,
      sym_operator,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [632] = 3,
    ACTIONS(178), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(180), 1,
      sym_white_space_control,
    STATE(26), 1,
      sym_statement_end,
  [642] = 1,
    ACTIONS(182), 1,
      anon_sym_PERCENT_RBRACE,
  [646] = 1,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
  [650] = 1,
    ACTIONS(186), 1,
      aux_sym_comment_token1,
  [654] = 1,
    ACTIONS(188), 1,
      anon_sym_POUND_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 45,
  [SMALL_STATE(12)] = 87,
  [SMALL_STATE(13)] = 126,
  [SMALL_STATE(14)] = 158,
  [SMALL_STATE(15)] = 190,
  [SMALL_STATE(16)] = 219,
  [SMALL_STATE(17)] = 248,
  [SMALL_STATE(18)] = 277,
  [SMALL_STATE(19)] = 306,
  [SMALL_STATE(20)] = 335,
  [SMALL_STATE(21)] = 364,
  [SMALL_STATE(22)] = 390,
  [SMALL_STATE(23)] = 416,
  [SMALL_STATE(24)] = 442,
  [SMALL_STATE(25)] = 468,
  [SMALL_STATE(26)] = 482,
  [SMALL_STATE(27)] = 496,
  [SMALL_STATE(28)] = 510,
  [SMALL_STATE(29)] = 524,
  [SMALL_STATE(30)] = 538,
  [SMALL_STATE(31)] = 552,
  [SMALL_STATE(32)] = 562,
  [SMALL_STATE(33)] = 572,
  [SMALL_STATE(34)] = 582,
  [SMALL_STATE(35)] = 592,
  [SMALL_STATE(36)] = 602,
  [SMALL_STATE(37)] = 612,
  [SMALL_STATE(38)] = 622,
  [SMALL_STATE(39)] = 632,
  [SMALL_STATE(40)] = 642,
  [SMALL_STATE(41)] = 646,
  [SMALL_STATE(42)] = 650,
  [SMALL_STATE(43)] = 654,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text, 2, 0, 3), SHIFT_REPEAT(7),
  [16] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inner_text, 2, 0, 3),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text, 2, 0, 3), SHIFT_REPEAT(20),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text, 2, 0, 3), SHIFT_REPEAT(5),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text, 2, 0, 3), SHIFT_REPEAT(2),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text, 2, 0, 3), SHIFT_REPEAT(6),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_content, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_content, 2, 0, 2),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inner_text, 1, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 2),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_begin, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_begin, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_begin, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_begin, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 3), SHIFT_REPEAT(32),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 3),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 3), SHIFT_REPEAT(19),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 3), SHIFT_REPEAT(21),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 3), SHIFT_REPEAT(36),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 3), SHIFT_REPEAT(34),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 3), SHIFT_REPEAT(17),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 3), SHIFT_REPEAT(22),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inner_text2, 2, 0, 3), SHIFT_REPEAT(35),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_end, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_end, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 2),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 2),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_end, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_end, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inner_text2, 1, 0, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [184] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jinja2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "jinja2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
